### ISSUE TITLE
일기작성 api 연결

### ISSUE THREAD

**Issue by YoungseoChoi23** [MoodBuddy/MoodBuddy-Web#39]
## Description
설명을 작성하세요.

## To-do
- [x] 일기 내용 데이터베이스에 저장 (텍스트 처리)
- [x] 이미지 처리
- [x] id 받아와서 diary/:id로 라우팅
- [x] 설정한 크기대로 이미지 크롭
- [x] 이미지 리다이렉팅
