### ISSUE TITLE
메인페이지 api 연결

### ISSUE THREAD

**Issue by m2na7** [MoodBuddy/MoodBuddy-Web#44]
## Description
메인페이지 api 연결

## To-do
- [x] 네비게이션바 프로필 설정
- [x] AnalysisSection에 프로필 출력
- [x] 달력기능 구현
- [x] 일기요약 api 연결
