### ISSUE TITLE
고민상담소 페이지

### ISSUE THREAD

**Issue by m2na7** [MoodBuddy/MoodBuddy-Web#9]
## Description
고민상담소 페이지 퍼블리싱

## To-do
- [x] 상담소 메인페이지
- [x] 편지 작성 페이지
- [x] 보내기 버튼 후 모달창
- [x] 답장 선택 후 모달창
- [x] 답장 안 왔을 때 페이지
- [x] 답장 왔을 때 페이지
